"""
references.py — Centralized Academic Bibliography for DAHS_2

All academic references used in the DAHS_2 project are collected here.
This serves two purposes:
  1. Backend can serve them via GET /api/references for the frontend.
  2. Acts as a single-source-of-truth bibliography for the project.

Usage:
    from src.references import REFERENCES
"""

REFERENCES = [
    {
        "key": "dekoster2007",
        "authors": "De Koster, R., Le-Duc, T., & Roodbergen, K.J.",
        "year": 2007,
        "title": "Design and control of warehouse order picking: A literature review",
        "journal": "European Journal of Operational Research",
        "volume": "182(2)",
        "pages": "481-501",
        "doi": "10.1016/j.ejor.2006.07.009",
        "used_for": "Zone structure, processing time variability (CV ~30%), worker utilization targets",
    },
    {
        "key": "gu2010",
        "authors": "Gu, J., Goetschalckx, M., & McGinnis, L.F.",
        "year": 2010,
        "title": "Research on warehouse design and performance evaluation: A comprehensive review",
        "journal": "European Journal of Operational Research",
        "volume": "203(3)",
        "pages": "539-549",
        "doi": "10.1016/j.ejor.2009.07.031",
        "used_for": "Arrival rates (60-150 orders/hr for mid-scale DCs), facility sizing, performance benchmarks",
    },
    {
        "key": "tompkins2010",
        "authors": "Tompkins, J.A., White, J.A., Bozer, Y.A., & Tanchoco, J.M.A.",
        "year": 2010,
        "title": "Facilities Planning",
        "journal": "Wiley (4th edition)",
        "volume": None,
        "pages": None,
        "doi": None,
        "used_for": "Processing time ranges for warehouse picking and packing operations",
    },
    {
        "key": "bartholdi2019",
        "authors": "Bartholdi, J.J. & Hackman, S.T.",
        "year": 2019,
        "title": "Warehouse & Distribution Science",
        "journal": "Georgia Institute of Technology (Release 0.98.1)",
        "volume": None,
        "pages": None,
        "doi": None,
        "used_for": "Batch arrival sizes (20-60 items/truck), receiving/shipping dock operations",
    },
    {
        "key": "inman1999",
        "authors": "Inman, R.R.",
        "year": 1999,
        "title": "Are you implementing a pull system by putting the cart before the horse?",
        "journal": "Production and Inventory Management Journal",
        "volume": "40(2)",
        "pages": "67-71",
        "doi": None,
        "used_for": "Equipment breakdown rates (2-5% of operational hours) in warehouse environments",
    },
    {
        "key": "goetschalckx1989",
        "authors": "Goetschalckx, M. & Ashayeri, J.",
        "year": 1989,
        "title": "Classification and design of order picking systems",
        "journal": "Logistics World",
        "volume": "2(2)",
        "pages": "99-106",
        "doi": None,
        "used_for": "Mean time to repair (MTTR) for conveyor/AGV equipment (10-30 min)",
    },
    {
        "key": "frazelle2016",
        "authors": "Frazelle, E.H.",
        "year": 2016,
        "title": "World-Class Warehousing and Material Handling",
        "journal": "McGraw-Hill (2nd edition)",
        "volume": None,
        "pages": None,
        "doi": None,
        "used_for": "Worker utilization benchmarks (65-85%), SLA breach norms for e-commerce fulfillment",
    },
    {
        "key": "garg2017",
        "authors": "Garg, D., Swami, M., & Bhagat, B.",
        "year": 2017,
        "title": "Impact of breaks on productivity and ergonomics in warehouse operations",
        "journal": "International Journal of Industrial Engineering",
        "volume": "24(3)",
        "pages": "181-192",
        "doi": None,
        "used_for": "Lunch productivity penalty factor (20-40% drop); calibrated to 1.3x (30%)",
    },
    {
        "key": "vepsalainen1987",
        "authors": "Vepsalainen, A.P.J. & Morton, T.E.",
        "year": 1987,
        "title": "Priority rules for job shops with weighted tardiness costs",
        "journal": "Management Science",
        "volume": "33(8)",
        "pages": "1035-1047",
        "doi": "10.1287/mnsc.33.8.1035",
        "used_for": "ATC (Apparent Tardiness Cost) dispatch rule formulation and K-factor selection",
    },
    {
        "key": "smith1956",
        "authors": "Smith, W.E.",
        "year": 1956,
        "title": "Various optimizers for single-stage production",
        "journal": "Naval Research Logistics Quarterly",
        "volume": "3(1-2)",
        "pages": "59-66",
        "doi": "10.1002/nav.3800030106",
        "used_for": "WSPT dispatch rule (optimal for weighted completion time on single machine)",
    },
    {
        "key": "pinedo2016",
        "authors": "Pinedo, M.L.",
        "year": 2016,
        "title": "Scheduling: Theory, Algorithms, and Systems",
        "journal": "Springer (5th edition)",
        "volume": None,
        "pages": None,
        "doi": "10.1007/978-3-319-26580-3",
        "used_for": "JSSP formulation, dispatch rule taxonomy (EDD, Slack, CR), critical ratio rule",
    },
    {
        "key": "burke2013",
        "authors": "Burke, E.K., Gendreau, M., Hyde, M., et al.",
        "year": 2013,
        "title": "Hyper-heuristics: A survey of the state of the art",
        "journal": "Journal of the Operational Research Society",
        "volume": "64(12)",
        "pages": "1695-1724",
        "doi": "10.1057/jors.2013.71",
        "used_for": "Hyper-heuristic framework: selection vs generation hyper-heuristics",
    },
    {
        "key": "cowling2001",
        "authors": "Cowling, P., Kendall, G., & Soubeiga, E.",
        "year": 2001,
        "title": "A hyperheuristic approach to scheduling a sales summit",
        "journal": "PATAT 2000, LNCS 2079",
        "volume": None,
        "pages": "176-190",
        "doi": None,
        "used_for": "Pioneering work on adaptive heuristic selection for scheduling problems",
    },
    {
        "key": "demsar2006",
        "authors": "Demsar, J.",
        "year": 2006,
        "title": "Statistical comparisons of classifiers over multiple data sets",
        "journal": "Journal of Machine Learning Research",
        "volume": "7",
        "pages": "1-30",
        "doi": None,
        "used_for": "Friedman test + Nemenyi post-hoc for multi-classifier comparison methodology",
    },
    {
        "key": "lundberg2017",
        "authors": "Lundberg, S.M. & Lee, S.I.",
        "year": 2017,
        "title": "A unified approach to interpreting model predictions",
        "journal": "Advances in Neural Information Processing Systems (NeurIPS 2017)",
        "volume": "30",
        "pages": "4765-4774",
        "doi": None,
        "used_for": "SHAP values for feature attribution in ML interpretability",
    },
]
